#!/usr/bin/env python3
"""Generate .env.example and docs/configuration.md from the settings inventory.

Hand-maintained configuration docs drift the moment someone adds a setting.
These are generated from ``app.settings.FIELDS`` — the same table the
application validates against — and CI re-runs this and fails if the committed
files differ, so documentation cannot silently fall behind the code.

    python3 tools/gen_config_docs.py           # write
    python3 tools/gen_config_docs.py --check   # verify, exit 1 on drift
"""
from __future__ import annotations

import argparse
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "backend"))

from app.settings import FIELDS, MIN_SECRET_LENGTH  # noqa: E402

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")

GROUPS = [
    ("Storage", ["DATA_DIR", "DATABASE_URL", "MIGRATE_FROM_SQLITE",
                 "USE_SHARED_POSTGRES", "POSTGRES_PROVISION_TOKEN"]),
    ("Security", ["SECRET_KEY", "JWT_HOURS", "DISABLE_AUTH", "ALLOW_REGISTRATION",
                  "MIN_PASSWORD_LENGTH"]),
    ("Network & proxy", ["PORT", "CORS_ORIGINS", "PROXY_HOPS", "RATELIMIT_ENABLED"]),
    ("AI providers", ["AI_PROVIDER", "AI_TIMEOUT_SECONDS", "AI_CONFIDENCE_THRESHOLD",
                      "ANTHROPIC_API_KEY", "CLAUDE_MODEL", "OPENAI_API_KEY",
                      "OPENAI_MODEL", "OPENAI_BASE_URL", "OLLAMA_URL", "OLLAMA_MODEL",
                      "OLLAMA_SEARCH_KEY", "OLLAMA_CLOUD_API_KEY", "OLLAMA_CLOUD_MODEL"]),
    ("Barcode identification", ["BARCODE_LOOKUP", "BARCODE_DB_URL", "BARCODE_DB_KEY"]),
    ("MCP (Home Assistant Assist)", ["MCP_ENABLED", "MCP_HOST", "MCP_PORT", "MCP_API",
                                     "MCP_API_TOKEN", "MCP_SERVER_TOKEN",
                                     "MCP_EXPOSE_EXTERNAL", "MCP_DEBUG_TOOLS"]),
    ("Serving & misc", ["WORKER_ENABLED", "MAX_UPLOAD_MB", "FRONTEND_DIST",
                        "DISCOVERY_HOST", "DEBUG"]),
    ("Logging", ["LOG_LEVEL", "SLOW_REQUEST_MS"]),
]


def _shown_default(f) -> str:
    if isinstance(f.default, tuple):
        return ",".join(f.default)
    if isinstance(f.default, bool):
        return "true" if f.default else "false"
    return str(f.default)


def _wrap(text: str, width: int) -> list[str]:
    words, lines, cur = text.split(), [], ""
    for w in words:
        if len(cur) + len(w) + 1 > width:
            lines.append(cur)
            cur = w
        else:
            cur = f"{cur} {w}".strip()
    if cur:
        lines.append(cur)
    return lines


def _check_groups_cover_every_field() -> None:
    """A field missing from GROUPS would be silently undocumented."""
    grouped = {n for _, names in GROUPS for n in names}
    declared = {f.name for f in FIELDS}
    missing, unknown = declared - grouped, grouped - declared
    if missing or unknown:
        raise SystemExit(
            f"gen_config_docs GROUPS is out of sync with FIELDS.\n"
            f"  missing from GROUPS: {sorted(missing)}\n"
            f"  in GROUPS but not declared: {sorted(unknown)}"
        )


def render_env_example() -> str:
    out = [
        "# HomeHoard configuration — EXAMPLE ONLY.",
        "#",
        "# Copy to .env and edit. Every value here is a placeholder: this file",
        "# contains NO usable secrets and is safe to commit.",
        "#",
        "# Generated by tools/gen_config_docs.py from the settings inventory.",
        "# Do not edit by hand — CI regenerates and diffs it.",
        "#",
        "# Full reference, including security impact: docs/configuration.md",
        "",
    ]
    by_name = {f.name: f for f in FIELDS}
    for title, names in GROUPS:
        out.append(f"# --- {title} " + "-" * max(0, 62 - len(title)))
        for name in names:
            f = by_name[name]
            for line in _wrap(f.doc, 74):
                out.append(f"# {line}")
            if f.secret:
                out.append(f"# SECRET. Also supported: {f.env_var}_FILE=/run/secrets/... "
                           "(Docker secrets)")
            out.append(f"#{f.env_var}={_shown_default(f)}")
            out.append("")
    # Compose-only knobs are NOT application settings — no Python reads them, so
    # they are deliberately absent from FIELDS. They still belong here: dropping
    # them when this file became generated would silently lose documentation the
    # docker-compose deployment depends on.
    out += [
        "# --- docker-compose only " + "-" * 39,
        "# Host address the MCP port is published on. Not read by the app: it is",
        "# consumed by docker-compose.yml when mapping the port. 127.0.0.1 keeps",
        "# MCP reachable only from this host; 0.0.0.0 exposes it on the LAN, which",
        "# requires HBOX_MCP_SERVER_TOKEN to be set.",
        "#HBOX_MCP_BIND=127.0.0.1",
        "",
    ]
    return "\n".join(out).rstrip() + "\n"


def render_reference() -> str:
    by_name = {f.name: f for f in FIELDS}
    out = [
        "# Configuration reference",
        "",
        "<!-- Generated by tools/gen_config_docs.py — do not edit by hand. -->",
        "",
        "Every setting HomeHoard understands. This table is generated from the same",
        "inventory the application validates against, so it cannot drift.",
        "",
        "## Precedence",
        "",
        "Highest wins:",
        "",
        "1. **Explicit config** passed to `create_app()` (tests, embedding).",
        "2. **Home Assistant add-on options** (`/data/options.json`).",
        "3. **Environment variables** (`HBOX_*`, or `HBOX_*_FILE` for secrets).",
        "4. **Built-in defaults.**",
        "",
        "Home Assistant options outrank the environment because, inside the add-on,",
        "options.json is the only surface an operator can edit — if the environment",
        "won, toggling a switch in the HA UI would silently do nothing. Outside Home",
        "Assistant the file does not exist, so the environment is authoritative.",
        "",
        "An empty environment variable (`HBOX_AI_PROVIDER=`) means *unset*, and falls",
        "through to the default rather than failing validation. The same applies to a",
        "cleared field in the Home Assistant UI, which writes an empty string.",
        "",
        "## Validation",
        "",
        "Configuration is validated once at startup, before the database is opened",
        "and before any port is bound. Invalid configuration prints **every** problem",
        "and refuses to start — it never surfaces later as a request-time 500.",
        "",
        "Booleans accept `1 true yes on` / `0 false no off` (any case). Anything else",
        "is an error: an unrecognised value is never silently treated as false.",
        "",
        "Check a deployment without starting it — this also prints which settings are",
        "non-default and where each came from, which is the fastest way to answer",
        "\"but I set that option\":",
        "",
        "```bash",
        "docker compose run --rm app python3 -m app.config_check",
        "```",
        "",
        "## Settings",
        "",
    ]
    for title, names in GROUPS:
        out += [f"### {title}", "",
                "| Variable | Type | Default | Secret | HA option | Notes |",
                "|---|---|---|---|---|---|"]
        for name in names:
            f = by_name[name]
            typ = getattr(f.parse, "__name__", "str")
            typ = {"parse": "enum/int", "parse_float": "number", "as_str": "string",
                   "parse_bool": "boolean", "csv_list": "list"}.get(typ, typ)
            default = _shown_default(f) or "_(empty)_"
            note = f.doc.replace("|", "/")
            if f.supports_file:
                note += f" Supports `{f.env_var}_FILE`."
            out.append(
                f"| `{f.env_var}` | {typ} | `{default}` | "
                f"{'**yes**' if f.secret else 'no'} | "
                f"{f'`{f.ha_option}`' if f.ha_option else '—'} | {note} |"
            )
        out.append("")

    out += [
        "## Security notes",
        "",
        f"- **`HBOX_SECRET_KEY`** must be at least {MIN_SECRET_LENGTH} characters when",
        "  authentication is enabled, and known placeholders are rejected outright.",
        "  Leave it unset and HomeHoard generates one **once** and persists it to",
        "  `$HBOX_DATA_DIR/.secret_key` (mode 0600). Back that file up with your data:",
        "  losing it logs everyone out and voids every issued API token. It has no",
        "  add-on option on purpose — a key that changed per boot would do exactly",
        "  that on every restart.",
        "- **`HBOX_DISABLE_AUTH=true` binds every request to one local user.** It is",
        "  correct behind Home Assistant ingress and wrong anywhere else. Combining it",
        "  with `HBOX_CORS_ORIGINS` is refused outright, because that would let any",
        "  listed website drive the API as that user.",
        "- **CORS is same-origin by default.** The SPA is served by the app itself, so",
        "  no cross-origin access is needed. Only add origins for a separate frontend",
        "  (e.g. the Vite dev server at `http://localhost:5173`). `*` is refused.",
        "- **`X-Forwarded-*` headers are ignored** unless `HBOX_PROXY_HOPS` says how",
        "  many proxies are in front. Trusting them by default would let any client",
        "  spoof its IP and evade rate limiting.",
        "- **`HBOX_MCP_EXPOSE_EXTERNAL`** makes the MCP server reachable from outside",
        "  Home Assistant. It is fail-closed: the server refuses to start unless a",
        "  Full- or MCP-scoped API key already exists, so it is never open.",
        "- **`HBOX_DATABASE_URL` is a secret** — it embeds the database password.",
        "  It is redacted everywhere HomeHoard reports configuration.",
        "",
        "## Deployment support",
        "",
        "- **Docker secrets**: any setting marked `Supports HBOX_*_FILE` can be read",
        "  from a file instead, e.g. `HBOX_SECRET_KEY_FILE=/run/secrets/homehoard_key`.",
        "- **Home Assistant add-on**: set options in the add-on's Configuration tab.",
        "  The `HA option` column above gives the key name.",
        "",
    ]
    return "\n".join(out).rstrip() + "\n"


TARGETS = [
    (".env.example", render_env_example),
    (os.path.join("docs", "configuration.md"), render_reference),
]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify the committed files match; exit 1 on drift")
    args = parser.parse_args(argv)

    _check_groups_cover_every_field()

    drifted = []
    for rel, render in TARGETS:
        path = os.path.join(ROOT, rel)
        content = render()
        if args.check:
            try:
                with open(path) as fh:
                    current = fh.read()
            except OSError:
                current = None
            if current != content:
                drifted.append(rel)
        else:
            os.makedirs(os.path.dirname(path), exist_ok=True) if os.path.dirname(rel) else None
            with open(path, "w") as fh:
                fh.write(content)
            print(f"wrote {rel}")

    if drifted:
        print("Generated configuration docs are out of date: " + ", ".join(drifted),
              file=sys.stderr)
        print("Run: python3 tools/gen_config_docs.py", file=sys.stderr)
        return 1
    if args.check:
        print("Generated configuration docs are in sync.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
